"""Lesezugriff auf das Expressions-``.h5ad`` (anndata) für MP-lite (Aufgabe 9).

Das ``.h5ad`` ist ein **Mediator-Artefakt** (``mediator/app/semantic/expression.py``
erzeugt es): eine Expressionsmatrix ``X`` (Proben × Gene, TPM) samt klinischer
``obs``-Metadaten (die volle Oviedo-Feldliste), ``var``-Gensymbolen und
vorberechneten 2D-Layouts in ``obsm`` (tSNE der Gen-/miRNA-Profile). MP-lite liest
daraus — **nur lesen**, nie schreiben; das Modul fasst weder ``mediator/`` noch
``wrappers/`` an, es öffnet lediglich die fertige Datei.

Alle Zugriffe sind **defensiv**: fehlt das Paket ``anndata`` oder die Datei, liefern
die Funktionen ``None``/leer, damit die App sauber auf den Graph-/Synthetik-Pfad
zurückfällt (kein harter Crash — siehe ``app.py`` Datenquellen-Priorität).

Pfad-Auflösung (in dieser Reihenfolge):
1. explizites ``path``-Argument,
2. ENV ``DATABRIDGE_H5AD``,
3. vorhandene Pancancer-Datei ``<repo>/wissensnetz/data/pancancer.h5ad``
   (Aufgabe 10; vom Abruf-Skript ``scripts/fetch_pancancer_h5ad.py`` erzeugt),
4. Default: das Referenz-``.h5ad`` unter
   ``<repo>/mediator/sample_data/tcga_brca_sample.h5ad``.

English: Read access to the expression ``.h5ad`` (anndata) for MP-lite
(task 9).

The ``.h5ad`` is a **mediator artifact** (``mediator/app/semantic/expression.py``
generates it): an expression matrix ``X`` (samples × genes, TPM) together
with clinical ``obs`` metadata (the full Oviedo field list), ``var`` gene
symbols and precomputed 2D layouts in ``obsm`` (tSNE of the gene/miRNA
profiles). MP-lite reads from it — **read only**, never writes; the module
touches neither ``mediator/`` nor ``wrappers/``, it merely opens the
finished file.

All access is **defensive**: if the ``anndata`` package or the file is
missing, the functions return ``None``/empty, so the app cleanly falls back
to the graph/synthetic path (no hard crash — see ``app.py``'s data-source
priority).

Path resolution (in this order):
1. explicit ``path`` argument,
2. ENV ``DATABRIDGE_H5AD``,
3. existing pancancer file ``<repo>/wissensnetz/data/pancancer.h5ad``
   (task 10; generated by the fetch script
   ``scripts/fetch_pancancer_h5ad.py``),
4. default: the reference ``.h5ad`` under
   ``<repo>/mediator/sample_data/tcga_brca_sample.h5ad``.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

try:  # anndata ist eine optionale Prototyp-Abhängigkeit (siehe README/pyproject).
    # EN: anndata is an optional prototype dependency (see README/pyproject).
    import anndata as _ad
except Exception:  # noqa: BLE001 (fehlt anndata -> sauberer Fallback, kein Crash)
    # EN: noqa: BLE001 (anndata missing -> clean fallback, no crash)
    _ad = None

try:
    import numpy as _np
except Exception:  # noqa: BLE001 (numpy kommt mit bokeh/anndata; ohne -> None)
    # EN: noqa: BLE001 (numpy comes with bokeh/anndata; without it -> None)
    _np = None

# ENV-Variable, mit der ein alternatives ``.h5ad`` (z. B. Pancancer-Export)
# vorgegeben werden kann, ohne Code zu ändern.
# EN: ENV variable used to specify an alternative ``.h5ad`` (e.g. a
# pancancer export) without changing code.
ENV_VAR = "DATABRIDGE_H5AD"

# Default-Pfad relativ zum Repo-Wurzelverzeichnis. Diese Datei liegt unter
# ``<repo>/wissensnetz/prototype/mp_lite/h5ad_source.py`` -> parents[3] == <repo>.
# EN: Default path relative to the repo root. This file lives under
# ``<repo>/wissensnetz/prototype/mp_lite/h5ad_source.py`` -> parents[3] ==
# <repo>.
_DEFAULT_REL = ("mediator", "sample_data", "tcga_brca_sample.h5ad")

# Pancancer-Datei (Aufgabe 10): wird — falls vorhanden — automatisch dem kleinen
# BRCA-Default vorgezogen. Erzeugt vom Abruf-Skript ``scripts/fetch_pancancer_h5ad.py``.
# EN: Pancancer file (task 10): automatically preferred over the small BRCA
# default if present. Generated by the fetch script
# ``scripts/fetch_pancancer_h5ad.py``.
_PANCANCER_REL = ("wissensnetz", "data", "pancancer.h5ad")

# Oviedo-``obs``-Spalten, die MP-lite für Hover/Färbung erwartet (Reihenfolge egal;
# fehlende Spalten werden zu ``None``). ``submitter_id`` = Case-Barcode (Rückkanal-
# und Kontext-Schlüssel), ``cancer`` = Kohorten-Code (Färbung/Legende).
# EN: Oviedo ``obs`` columns that MP-lite expects for hover/coloring (order
# irrelevant; missing columns become ``None``). ``submitter_id`` = case
# barcode (feedback-channel and context key), ``cancer`` = cohort code
# (coloring/legend).
_OBS_FIELDS = (
    "sample_type", "submitter_id", "project_id", "race", "sex_at_birth", "ethnicity",
    "vital_status", "tumor_stage", "morphology", "site_of_resection_or_biopsy",
    "has_metastasis", "primary_diagnosis", "age_at_diagnosis", "cancer",
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def default_h5ad_path() -> Path:
    """Referenz-``.h5ad`` unter ``<repo>/mediator/sample_data/tcga_brca_sample.h5ad``.

    English: Reference ``.h5ad`` under
    ``<repo>/mediator/sample_data/tcga_brca_sample.h5ad``.
    """
    return _repo_root().joinpath(*_DEFAULT_REL)


def pancancer_h5ad_path() -> Path:
    """Pancancer-``.h5ad`` (Aufgabe 10) unter ``<repo>/wissensnetz/data/pancancer.h5ad``.

    English: Pancancer ``.h5ad`` (task 10) under
    ``<repo>/wissensnetz/data/pancancer.h5ad``.
    """
    return _repo_root().joinpath(*_PANCANCER_REL)


def resolve_h5ad_path(path: str | os.PathLike[str] | None = None) -> Path:
    """Pfad auflösen: explizites ``path`` > ENV ``DATABRIDGE_H5AD`` > vorhandene
    Pancancer-Datei (Aufgabe 10) > BRCA-Default.

    So zeigt MP-Lite nach ``scripts/fetch_pancancer_h5ad.py`` automatisch die
    Pancancer-Karte, ohne dass ENV gesetzt werden muss; fehlt die Datei, bleibt es
    beim BRCA-Fixture wie in Aufgabe 9.

    English: Resolves the path: explicit ``path`` > ENV ``DATABRIDGE_H5AD``
    > existing pancancer file (task 10) > BRCA default.

    This way MP-Lite automatically shows the pancancer map after
    ``scripts/fetch_pancancer_h5ad.py``, without ENV needing to be set; if
    the file is missing, it stays with the BRCA fixture as in task 9.
    """
    if path:
        return Path(path)
    env = os.environ.get(ENV_VAR)
    if env:
        return Path(env)
    pancancer = pancancer_h5ad_path()
    if pancancer.exists():
        return pancancer
    return default_h5ad_path()


def load_h5ad(path: str | os.PathLike[str] | None = None) -> Any | None:
    """``AnnData`` laden oder ``None`` (fehlendes ``anndata``, fehlende/kaputte Datei).

    Bewusst tolerant: jeder Fehler führt zu ``None`` statt zu einer Exception, damit
    die aufrufende App auf den nächsten Datenquellen-Pfad zurückfallen kann.

    English: Loads ``AnnData`` or returns ``None`` (missing ``anndata``,
    missing/corrupt file).

    Deliberately tolerant: any error leads to ``None`` instead of an
    exception, so the calling app can fall back to the next data-source
    path.
    """
    if _ad is None:
        return None
    p = resolve_h5ad_path(path)
    if not p.exists():
        return None
    try:
        return _ad.read_h5ad(p)
    except Exception:  # noqa: BLE001 (kaputte/inkompatible Datei -> Fallback)
        # EN: noqa: BLE001 (corrupt/incompatible file -> fallback)
        return None


def _isna(v: object) -> bool:
    """``True`` für ``None``/NaN/pandas-``NA`` — sonst ``False`` (robust ohne harte
    pandas-Abhängigkeit).

    English: ``True`` for ``None``/NaN/pandas ``NA`` — otherwise ``False``
    (robust without a hard pandas dependency).
    """
    if v is None:
        return True
    try:  # pandas ist mit anndata da; NaN/NA sauber erkennen.
        # EN: pandas is present alongside anndata; detect NaN/NA cleanly.
        import pandas as pd

        return bool(pd.isna(v))
    except Exception:  # noqa: BLE001
        return isinstance(v, float) and v != v  # NaN != NaN / EN: NaN != NaN


def _clean(v: object) -> object | None:
    """Rohwert -> Python-Wert oder ``None`` (fehlend). numpy-Skalare -> Python.

    English: Raw value -> Python value or ``None`` (missing). numpy scalars -> Python.
    """
    if _isna(v):
        return None
    if _np is not None and isinstance(v, _np.generic):
        return v.item()
    return v


def points_from_obs(adata: Any) -> list[dict]:
    """Eine Zeile je Sample aus ``obs`` — mit den Oviedo-Hover-Feldern, ``cancer``
    und ``tumor`` (= ``submitter_id``, Case-Barcode; Fallback: ``obs``-Index).

    Rückgabe: Liste von Dicts in ``obs``-Reihenfolge. Fehlende Werte sind ``None``.
    Jede Zeile enthält zusätzlich ``sample_id`` (den ``obs``-Index).

    English: One row per sample from ``obs`` — with the Oviedo hover
    fields, ``cancer`` and ``tumor`` (= ``submitter_id``, case barcode;
    fallback: ``obs`` index).

    Returns: list of dicts in ``obs`` order. Missing values are ``None``.
    Every row additionally contains ``sample_id`` (the ``obs`` index).
    """
    obs = adata.obs
    cols = set(obs.columns)
    rows: list[dict] = []
    for sample_id, row in obs.iterrows():
        rec: dict[str, object | None] = {"sample_id": str(sample_id)}
        for col in _OBS_FIELDS:
            rec[col] = _clean(row[col]) if col in cols else None
        submitter = rec.get("submitter_id")
        rec["tumor"] = submitter if submitter not in (None, "") else str(sample_id)
        rows.append(rec)
    return rows


def marker_column(adata: Any, symbol: str) -> Any | None:
    """Expressionsspalte eines Gensymbols aus ``X`` — per ``var["symbol"]``-Lookup.

    Rückgabe: 1D-``float``-``np.ndarray`` (Länge = Anzahl Proben) oder ``None``, wenn
    das Symbol nicht in ``var`` vorkommt (bzw. ``numpy``/``var["symbol"]`` fehlt).

    English: Expression column of a gene symbol from ``X`` — via a
    ``var["symbol"]`` lookup.

    Returns: 1D ``float`` ``np.ndarray`` (length = number of samples) or
    ``None`` if the symbol does not occur in ``var`` (or
    ``numpy``/``var["symbol"]`` is missing).
    """
    if _np is None:
        return None
    var = adata.var
    if "symbol" not in var.columns:
        return None
    mask = (var["symbol"].astype(str).to_numpy() == str(symbol))
    if not mask.any():
        return None
    idx = int(_np.flatnonzero(mask)[0])
    col = adata.X[:, idx]
    try:  # sparse-Matrix -> dichtes 1D-Array
        # EN: sparse matrix -> dense 1D array
        col = col.toarray()
    except Exception:  # noqa: BLE001 (schon dicht)
        # EN: noqa: BLE001 (already dense)
        pass
    return _np.asarray(col, dtype=float).ravel()


def layout(adata: Any, key: str) -> Any | None:
    """Vorberechnetes 2D-Layout aus ``obsm[key]`` (z. B. ``"X_tsne_genes"``).

    Rückgabe: ``(n, 2)``-``float``-``np.ndarray`` oder ``None``, wenn der Key fehlt
    oder das Array nicht mindestens zweidimensional ist.

    English: Precomputed 2D layout from ``obsm[key]`` (e.g.
    ``"X_tsne_genes"``).

    Returns: ``(n, 2)`` ``float`` ``np.ndarray`` or ``None`` if the key is
    missing or the array is not at least two-dimensional.
    """
    if _np is None:
        return None
    if key not in adata.obsm:
        return None
    arr = _np.asarray(adata.obsm[key], dtype=float)
    if arr.ndim != 2 or arr.shape[1] < 2:
        return None
    return arr[:, :2]
